---
title: "Session 9: GitHub"
description: |
  Learn how to use GitHub Desktop for version control.
author:
  - name: Sam Langton
    url: https://www.samlangton.info/
    affiliation: Amsterdam UMC
    affiliation_url: https://www.amsterdamumc.org/en.htm
date: 12-04-2024
output:
  distill::distill_article:
    self_contained: false
---

In this session we will learn how to use GitHub Desktop for version control. Once you've mastered the basics of version control using GitHub Desktop, you will be better able to track changes to your own code, revert to old versions of your scripts, collaborate with others, and avoid the worry of losing your work.

You are welcome to sit back and listen, but if you'd like to actively follow along with the exercise during the workshop, please prepare the following steps beforehand:

1. [Sign-up](https://github.com/) to GitHub.
2. [Download](https://github.com/apps/desktop) GitHub Desktop.
3. Sign-in to your GitHub account within GitHub Desktop.
4. [Download the example R project](https://github.com/langtonhugh/github_desktop/raw/refs/heads/main/example_project.zip) that we will work with. Unzip it and place the folder somewhere on your local machine. 

## Material

The material for the session is available [here](https://rpubs.com/langton_/githubdesktop).



